---
- name: Git clone app repo to /home/
  git:
    repo: "https://github.com/Gustavo-SF/PPP-Search-App.git"
    dest: /home/mota-engil/{{ app_name }}/

- name: Install requirements.txt
  pip:
    requirements: /home/mota-engil/{{ app_name }}/requirements.txt
    virtualenv: /home/mota-engil/{{ app_name }}/venv
    virtualenv_python: python3.6

- name: Send the .env file
  template:
    src: .env_template
    dest: /home/mota-engil/{{ app_name }}/.env

- name: Install gunicorn
  pip:
    name:
      - gunicorn
    virtualenv: /home/mota-engil/{{ app_name }}/venv

- name: Copy supervisor configuration file
  template:
    src: search_app.conf
    dest: /etc/supervisor/conf.d/{{ app_name }}.conf
  notify: reload supervisor

- name: Copy nginx configuration for API
  template:
    src: api.conf
    dest: /etc/nginx/conf.d/api.conf
  notify: reload nginx

- meta: flush_handlers